from mydatasets.get_cifar10 import get_cifar10
from mydatasets.get_cifar100 import get_cifar100
from mydatasets.get_celeba import get_celebA
from mydatasets.get_iwildcam import get_iwildcam
from mydatasets.get_imagenet import get_imagenet
from mydatasets.get_domainbed import get_domainbed
from mydatasets.get_mnist import get_mnist
from mydatasets.get_webvision import get_webvision
from mydatasets.get_ilsvrc12 import get_ilsvrc12